### ISSUE TITLE
[Comparison Template] Incorrectly renderred

### ISSUE THREAD

**Issue by tespirit** [beautifulai/beautifulai_issues#10]
<img width="887" alt="screen shot 2017-09-13 at 10 38 53 am" src="https://user-images.githubusercontent.com/73727/30391858-c6d26b32-986f-11e7-844d-020442a55d5e.png">

Marketing template is rendering the comparison bar incorrectly:
https://www.beautiful.ai/player/-Ks5h-ndE7sfUR99vFMg/Marketing-Campaign-Plan-Template/7

**Comment by iseekbeauty** [comment]
might we want to do something like this @mitchgrasso? Seems like it would be useful where one value is much larger than others.

![image](https://user-images.githubusercontent.com/1149577/30392792-be1c2868-9872-11e7-97b0-d4d0187720cd.png)

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#486
