### ISSUE TITLE
Text Wrapping: Tray images causes text to be clipped

### ISSUE THREAD

**Issue by fatimasbeih** [beautifulai/beautifulai_issues#11]
**Description of issue**: I created a ‘Photos with Text’ slide. I added 5 photos with text on each slide. I added a tray image. .In the layouts options, I clicked “above’ for my text block. When I do this, text wrapping is fine. When I click below, text wrapping gets condensed/clipped.. 

**Test Steps**: 

1. Create ‘photos with text’ slide
2. Add 5 photo boxes/items
3. Include text that is 3 lines long
4. Add tray images. 
5. Click on Layout>>Text Block>>and toggle between ABOVE/BELOW

**Expected result**: That I can add an image, without text clipping or disappearing
**Actual Result**: adding a tray image causes the text to clip

**Comment:** Without tray images, included the text block above or below works fine, no text is clipped. However, adding a tray image clips the text partially or entirely. More complexities with this includes adding a text block and its position with the position of the tray image. 

**text block below:**
![image](https://user-images.githubusercontent.com/31864897/30391707-44f4de88-986f-11e7-80d3-e41a61e2a3a6.png)

**text block above:**
![image](https://user-images.githubusercontent.com/31864897/30391776-89e3d530-986f-11e7-947f-7aadcd7488a2.png)

**bottom tray image causes entire text to disappear**
![image](https://user-images.githubusercontent.com/31864897/30392480-d5f88770-9871-11e7-97f3-087ca1ae6f91.png)

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#487
