### ISSUE TITLE
Section Break: No character limit in ‘Section' bubble, text extends off slide 

### ISSUE THREAD

**Issue by fatimasbeih** [beautifulai/beautifulai_issues#12]
**Description of issue**: In the section break slide, there is no character limit and text extends off of the slide.   

**Test Steps**: 

1. Create ‘Section Break’ slide
2. Add the Star Wars opening crawl repeatedly
3. Then add a description

**Expected result**: Text in section bubble wraps
**Actual Result**: extends off of the slide

**Comment**: Interestingly, when you add a description, the bubble and text readjusts itself .Also, adding a tray image will correct the text extension off the slide. 

cut off text 
![image](https://user-images.githubusercontent.com/31864897/30395008-b44445d0-9879-11e7-91fb-aa23f87f069d.png)

readjusted text 
![image](https://user-images.githubusercontent.com/31864897/30395103-f878561a-9879-11e7-844c-d958bce1765f.png)

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#488
