### ISSUE TITLE
Data & Charts: Phantom data included on X-axis 

### ISSUE THREAD

**Issue by fatimasbeih** [beautifulai/beautifulai_issues#3]
Description of issue: I created a chart with the x-axis numbers from 1900-2000, in increments of 10 years. Instead of the chart reflecting my numbers, Beautiful ai added years to the X-axis

Test Steps: 
1.Create line or coloumn chart
2. Add 7 entries on the x-axis(everything normal)
3. Add an 8th entry chart slide

Expected result: X-axis to reflect 8 years, (1910, 1920, 1930, etc)

Actual Result: the platform added numbers in between my 10 year incriments

![untitled](https://user-images.githubusercontent.com/31864897/30302486-3a02c490-9716-11e7-8987-279af4cf3978.png)

More Details:
I tested this on Line Chart, area chart,  Column Chart.--same results

Inconsistencies: I assumed the threshold was 7 (in line chart it is 7). In area chart, the threshold is 5 before it adds data.

**Comment by benjanik** [comment]
@fatimasbeih - the actual feature here is auto detection of date data converting the chart from "category chart" to "time series chart"

@mitchgrasso - how do you feel about this data being auto converted? this is similar to our "Jan, Feb, Mar" data example in that it isn't a complete date, but our only reliable date parsing library thinks it is.

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#481
