### ISSUE TITLE
Video: When adding a video to slide, URL included in title 

### ISSUE THREAD

**Issue by fatimasbeih** [beautifulai/beautifulai_issues#4]
Description of issue: When adding a video to a slide, the URL of the video shows up in the title 

Test Steps: 
1.Create a slide using the 'Video with Title" template
2. Type a title 
3. Add a video 

Expected result: The video will add with no change to the title
Actual Result: The video was added, but the URL showed up in the title as well

I noticed that if the cursor is still blinking in the title, the url gets added there. If you move your mouse out of that box (click anywhere on the slide) the video uploads fine and the URL is not added to the title

Gif  1: cursor remains in title, url added to title
![links in title](https://user-images.githubusercontent.com/31864897/30349635-7655cef8-97c8-11e7-8bf6-b9ceb0529d15.gif)

Gif 2: Cursor is not in title, no change to title
![no cursor in box](https://user-images.githubusercontent.com/31864897/30349923-89820702-97c9-11e7-9969-45315671214a.gif)

Screenshot:
![image](https://user-images.githubusercontent.com/31864897/30350125-611b2428-97ca-11e7-8b66-823f5685c06f.png)

**Comment by fatimasbeih** [comment]
This issue can also be found in Line Charts. 

![charts aswell](https://user-images.githubusercontent.com/31864897/30350604-442d32fa-97cc-11e7-95df-c98db85e047a.gif)

**Comment by fatimasbeih** [comment]
After closing out and opening the power-point, the additions to the titles have gone away. This can still be confusing and bothersome to our users while it is happening.

**Comment by fatimasbeih** [comment]
inconsistencies: in some cases, after closing out the presentation and opening it away, the additions to the title went away and in some cases, they stayed.

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#482
