### ISSUE TITLE
Performance: Deck with 34 slides takes too long to load.

### ISSUE THREAD

**Issue by tespirit** [beautifulai/beautifulai_issues#5]
Goto: https://www.beautiful.ai/player/-Ktm2qebTuR5xCMb2uIJ/This-is-where-the-title-goes

It takes a while to load and turns your computer into a heater.

**Comment by benjanik** [comment]
The underlying issue here is that our jpg renderer appears to be failing silently.

**Comment by benjanik** [comment]
Fixed by https://github.com/beautifulai/beautifulai/commit/429db25e57ed619a62d095473133df0c46d43dcb

Performance will be better by using jpg placeholders and not rendering all slides as SVG.
