### ISSUE TITLE
Text Wrapping: Continuous text with no spaces extends into nothingness

### ISSUE THREAD

**Issue by fatimasbeih** [beautifulai/beautifulai_issues#7]
**Description of issue:** Continuous text with no spaces extends into nothingness

**Test Steps:** 
1.Create bullet points slide
2. Type continuous text without adding a space. Either type or paste. I pasted a URL
3. Add a left tray or a right tray .The text extends over the image
4. Even if there was no image, the text will extend past the text box and it looks bad

**Expected result**: Text would wrap or hyphenate
**Actual Result**: Text keeps going and does not wrap

**right tray** 
![image](https://user-images.githubusercontent.com/31864897/30354788-a033aee6-97e3-11e7-8457-74620b2d109f.png)

** #left tray** 

![image](https://user-images.githubusercontent.com/31864897/30387985-22a2eade-9863-11e7-968e-badce00008e4.png)

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#483
