### ISSUE TITLE
Library: Only ‘Add Slide’ option in right-click presentation works. 

### ISSUE THREAD

**Issue by fatimasbeih** [beautifulai/beautifulai_issues#8]
**Description of issue**: Only ‘Add Slide’ option in right-click presentation works. 
**Test Steps**: 
1.Right click your presentation from the home page
2. Click through the options (Add slide, Duplicate slide, delete slide, next slide, and previous slide)
3. Only ‘Add slide’ works.

**Expected result**: That all options would work
**Actual Result**: ‘Add slide’ works only

I’m curious why these would be options since it seems a bit dangerous that someone can delete their slide from this view. 

![image](https://user-images.githubusercontent.com/31864897/30388720-655ea29e-9865-11e7-8a02-f8d32f964936.png)

**Comment by benjanik** [comment]
This is actually the slide grid context menu, which shouldn't show in presentation view.

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#484
