### ISSUE TITLE
Images: Unable to edit/change image without refreshing 

### ISSUE THREAD

**Issue by fatimasbeih** [beautifulai/beautifulai_issues#9]
**Description of issue**: When adding an image, I am unable to edit the image or change the image without refreshing my browser
**Test Steps**: 
1.Add an iimage to a slide
2. Attempt to change the image or edit its location/resize the image
3. Refresh the page
4. Try to edit and change the image now, you should be successful

**Expected result**: Edit or change an image without refreshing 
**Actual Result**: refresh session then change and/or edit an image

![image refresh](https://user-images.githubusercontent.com/31864897/30391330-d1012bfe-986d-11e7-832d-48cbd4ded215.gif)

**Comment by fatimasbeih** [comment]
I am seeing that I am also unable to change text after adding an image. I added a tray image to a headline slide, and wanted to change my headline, but was unable to until after I refreshed.

**Comment by tespirit** [comment]
This issue was moved to beautifulai/beautifulai#485
